# Copyright (C) 2022, Gauthier Leonard
# See the file LICENSE for licensing terms.
---
avalanchego_version: 1.9.6
avalanchego_network_id: local

avalanchego_https_enabled: false
avalanchego_https_local_certs_dir: "{{ inventory_dir }}/../../files/https"

avalanchego_staking_use_local_certs: true
avalanchego_staking_local_certs_dir: "{{ inventory_dir }}/../../files/staking"

avalanchego_vms_install: []

avalanchego_track_subnets: []

avalanchego_node_json:
  # Adapt Snow consensus parameters to a 5-node network
  snow-sample-size: 3
  snow-quorum-size: 2
  snow-mixed-query-num-push-vdr: 2
