# Copyright (C) 2022, Gauthier Leonard
# See the file LICENSE for licensing terms.
---
avalanchego_version: 1.9.0
avalanchego_network_id: fuji
# AvalancheGo will generate new certs if needed
avalanchego_use_existing_certs: no
# Whitelisting the SpacesVM subnet
avalanche_whitelisted_subnets: Ai42MkKqk8yjXFCpoHXw7rdTWSHiKEMqh5h8gbxwjgkCUfkrk
# Installing the SpacesVM
avalanchego_vms_install:
  - spacesvm=0.0.9
